"""recreate run_new_checks

Revision ID: 59453803171e
Revises: 70a97aad3eaa
Create Date: 2026-04-01 12:25:42.972807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59453803171e'
down_revision: Union[str, Sequence[str], None] = '70a97aad3eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_new_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.String(length=100), nullable=False),
    sa.Column('client_region', sa.String(length=100), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('content_placement', sa.Text(), nullable=True),
    sa.Column('proofreading', sa.Text(), nullable=True),
    sa.Column('missing_content', sa.Text(), nullable=True),
    sa.Column('sitemap_url', sa.String(length=500), nullable=True),
    sa.Column('skip_incomplete', sa.Boolean(), nullable=True),
    sa.Column('meeting_notes', sa.Text(), nullable=True),
    sa.Column('client_emails', sa.Text(), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('deadlines', sa.Text(), nullable=True),
    sa.Column('overall_deadline', sa.String(length=100), nullable=True),
    sa.Column('brand_notes', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=100), nullable=True),
    sa.Column('secondary_colors', sa.Text(), nullable=True),
    sa.Column('primary_font', sa.String(length=100), nullable=True),
    sa.Column('secondary_font', sa.String(length=100), nullable=True),
    sa.Column('theme_demo_url', sa.String(length=500), nullable=True),
    sa.Column('theme_desc', sa.Text(), nullable=True),
    sa.Column('competitor_refs', sa.Text(), nullable=True),
    sa.Column('design_prefs_desc', sa.Text(), nullable=True),
    sa.Column('custom_layout', sa.Text(), nullable=True),
    sa.Column('priority_pages', sa.Text(), nullable=True),
    sa.Column('forms_list', sa.Text(), nullable=True),
    sa.Column('form_fields', sa.Text(), nullable=True),
    sa.Column('captcha_details', sa.Text(), nullable=True),
    sa.Column('captcha_behavior', sa.Text(), nullable=True),
    sa.Column('form_submission_flows', sa.Text(), nullable=True),
    sa.Column('interactive_elements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interactive_behavior', sa.Text(), nullable=True),
    sa.Column('third_party_integrations', sa.Text(), nullable=True),
    sa.Column('seo_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canonical_urls', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('header_structure', sa.Text(), nullable=True),
    sa.Column('sitemap_index_notes', sa.Text(), nullable=True),
    sa.Column('og_tags', sa.Text(), nullable=True),
    sa.Column('schema_markup', sa.Text(), nullable=True),
    sa.Column('robots_txt', sa.Text(), nullable=True),
    sa.Column('compression_rules', sa.Text(), nullable=True),
    sa.Column('naming_conventions', sa.Text(), nullable=True),
    sa.Column('priority_media', sa.Text(), nullable=True),
    sa.Column('auto_optimize', sa.Boolean(), nullable=True),
    sa.Column('accessibility_standard', sa.String(length=100), nullable=True),
    sa.Column('custom_accessibility', sa.Text(), nullable=True),
    sa.Column('device_sizes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_devices', sa.Text(), nullable=True),
    sa.Column('browsers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('browser_notes', sa.Text(), nullable=True),
    sa.Column('alt_text_req', sa.Text(), nullable=True),
    sa.Column('text_resizing', sa.Text(), nullable=True),
    sa.Column('high_contrast', sa.Text(), nullable=True),
    sa.Column('keyboard_nav', sa.Text(), nullable=True),
    sa.Column('aria_labels', sa.Text(), nullable=True),
    sa.Column('accessibility_priority_pages', sa.Text(), nullable=True),
    sa.Column('accessibility_notes', sa.Text(), nullable=True),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=True),
    sa.Column('ssl_details', sa.Text(), nullable=True),
    sa.Column('redirects', sa.Text(), nullable=True),
    sa.Column('redirects_verified', sa.Boolean(), nullable=True),
    sa.Column('scripts_code', sa.Text(), nullable=True),
    sa.Column('performance_notes', sa.Text(), nullable=True),
    sa.Column('third_party_integrations_sec', sa.Text(), nullable=True),
    sa.Column('custom_404', sa.Text(), nullable=True),
    sa.Column('custom_500', sa.Text(), nullable=True),
    sa.Column('other_errors', sa.Text(), nullable=True),
    sa.Column('error_handling_notes', sa.Text(), nullable=True),
    sa.Column('priority_technical_checks', sa.Text(), nullable=True),
    sa.Column('backup_notes', sa.Text(), nullable=True),
    sa.Column('report_recipients', sa.Text(), nullable=True),
    sa.Column('report_format', sa.String(length=100), nullable=True),
    sa.Column('severity_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kpi_selected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_selected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_weekly', sa.Boolean(), nullable=True),
    sa.Column('qa_comments', sa.Text(), nullable=True),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.Column('summary_metrics', sa.Text(), nullable=True),
    sa.Column('content_ai_result', sa.JSON(), nullable=True),
    sa.Column('design_ai_result', sa.JSON(), nullable=True),
    sa.Column('seo_ai_result', sa.JSON(), nullable=True),
    sa.Column('accessibility_ai_result', sa.JSON(), nullable=True),
    sa.Column('technical_ai_result', sa.JSON(), nullable=True),
    sa.Column('report_result', sa.JSON(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_new_checks_id'), 'run_new_checks', ['id'], unique=False)
    op.create_index(op.f('ix_run_new_checks_project_id'), 'run_new_checks', ['project_id'], unique=True)
    op.drop_index(op.f('ix_asset_set_assets_asset_id'), table_name='asset_set_assets')
    op.drop_index(op.f('ix_asset_set_assets_asset_set_id'), table_name='asset_set_assets')
    op.drop_index(op.f('ix_asset_set_assets_client_id'), table_name='asset_set_assets')
    op.drop_index(op.f('ix_asset_set_assets_id'), table_name='asset_set_assets')
    op.drop_table('asset_set_assets')
    op.drop_index(op.f('ix_conversion_actions_client_id'), table_name='conversion_actions')
    op.drop_index(op.f('ix_conversion_actions_google_conversion_action_id'), table_name='conversion_actions')
    op.drop_index(op.f('ix_conversion_actions_id'), table_name='conversion_actions')
    op.drop_table('conversion_actions')
    op.drop_index(op.f('ix_assets_client_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_google_asset_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_campaign_asset_performance_asset_id'), table_name='campaign_asset_performance')
    op.drop_index(op.f('ix_campaign_asset_performance_campaign_id'), table_name='campaign_asset_performance')
    op.drop_index(op.f('ix_campaign_asset_performance_client_id'), table_name='campaign_asset_performance')
    op.drop_index(op.f('ix_campaign_asset_performance_id'), table_name='campaign_asset_performance')
    op.drop_table('campaign_asset_performance')
    op.drop_index(op.f('ix_bidding_strategies_client_id'), table_name='bidding_strategies')
    op.drop_index(op.f('ix_bidding_strategies_google_bidding_strategy_id'), table_name='bidding_strategies')
    op.drop_index(op.f('ix_bidding_strategies_id'), table_name='bidding_strategies')
    op.drop_table('bidding_strategies')
    op.drop_index(op.f('ix_campaign_asset_set_links_asset_set_id'), table_name='campaign_asset_set_links')
    op.drop_index(op.f('ix_campaign_asset_set_links_campaign_id'), table_name='campaign_asset_set_links')
    op.drop_index(op.f('ix_campaign_asset_set_links_client_id'), table_name='campaign_asset_set_links')
    op.drop_index(op.f('ix_campaign_asset_set_links_id'), table_name='campaign_asset_set_links')
    op.drop_table('campaign_asset_set_links')
    op.drop_index(op.f('ix_customer_asset_set_links_asset_set_id'), table_name='customer_asset_set_links')
    op.drop_index(op.f('ix_customer_asset_set_links_client_id'), table_name='customer_asset_set_links')
    op.drop_index(op.f('ix_customer_asset_set_links_id'), table_name='customer_asset_set_links')
    op.drop_table('customer_asset_set_links')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_campaign_conversion_stats_campaign_id'), table_name='campaign_conversion_stats')
    op.drop_index(op.f('ix_campaign_conversion_stats_client_id'), table_name='campaign_conversion_stats')
    op.drop_index(op.f('ix_campaign_conversion_stats_conversion_action_id'), table_name='campaign_conversion_stats')
    op.drop_index(op.f('ix_campaign_conversion_stats_id'), table_name='campaign_conversion_stats')
    op.drop_table('campaign_conversion_stats')
    op.drop_index(op.f('ix_asset_sets_client_id'), table_name='asset_sets')
    op.drop_index(op.f('ix_asset_sets_google_asset_set_id'), table_name='asset_sets')
    op.drop_index(op.f('ix_asset_sets_id'), table_name='asset_sets')
    op.drop_table('asset_sets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_sets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('google_asset_set_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('asset_sets_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_sets_pkey')),
    sa.UniqueConstraint('resource_name', name=op.f('asset_sets_resource_name_key'))
    )
    op.create_index(op.f('ix_asset_sets_id'), 'asset_sets', ['id'], unique=False)
    op.create_index(op.f('ix_asset_sets_google_asset_set_id'), 'asset_sets', ['google_asset_set_id'], unique=False)
    op.create_index(op.f('ix_asset_sets_client_id'), 'asset_sets', ['client_id'], unique=False)
    op.create_table('campaign_conversion_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conversion_action_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conversion_action_resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('conversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('conversions_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('all_conversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('all_conversions_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('view_through_conversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cost_per_conversion', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cost_per_all_conversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('campaign_conversion_stats_campaign_id_fkey')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('campaign_conversion_stats_client_id_fkey')),
    sa.ForeignKeyConstraint(['conversion_action_id'], ['conversion_actions.id'], name=op.f('campaign_conversion_stats_conversion_action_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_conversion_stats_pkey'))
    )
    op.create_index(op.f('ix_campaign_conversion_stats_id'), 'campaign_conversion_stats', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_conversion_stats_conversion_action_id'), 'campaign_conversion_stats', ['conversion_action_id'], unique=False)
    op.create_index(op.f('ix_campaign_conversion_stats_client_id'), 'campaign_conversion_stats', ['client_id'], unique=False)
    op.create_index(op.f('ix_campaign_conversion_stats_campaign_id'), 'campaign_conversion_stats', ['campaign_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(), server_default=sa.text("'Unassigned'::character varying"), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('word_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_code_file', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('score_overall', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('score_seo', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('score_accessibility', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('score_performance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('score_security', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('issues_critical', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('issues_high', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('issues_medium', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('issues_low', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_results_pkey')),
    sa.UniqueConstraint('file_id', name=op.f('analysis_results_file_id_key'))
    )
    op.create_table('customer_asset_set_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_set_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_set_id'], ['asset_sets.id'], name=op.f('customer_asset_set_links_asset_set_id_fkey')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('customer_asset_set_links_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_asset_set_links_pkey'))
    )
    op.create_index(op.f('ix_customer_asset_set_links_id'), 'customer_asset_set_links', ['id'], unique=False)
    op.create_index(op.f('ix_customer_asset_set_links_client_id'), 'customer_asset_set_links', ['client_id'], unique=False)
    op.create_index(op.f('ix_customer_asset_set_links_asset_set_id'), 'customer_asset_set_links', ['asset_set_id'], unique=False)
    op.create_table('campaign_asset_set_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_set_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_set_id'], ['asset_sets.id'], name=op.f('campaign_asset_set_links_asset_set_id_fkey')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('campaign_asset_set_links_campaign_id_fkey')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('campaign_asset_set_links_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_asset_set_links_pkey'))
    )
    op.create_index(op.f('ix_campaign_asset_set_links_id'), 'campaign_asset_set_links', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_asset_set_links_client_id'), 'campaign_asset_set_links', ['client_id'], unique=False)
    op.create_index(op.f('ix_campaign_asset_set_links_campaign_id'), 'campaign_asset_set_links', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_asset_set_links_asset_set_id'), 'campaign_asset_set_links', ['asset_set_id'], unique=False)
    op.create_table('bidding_strategies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('google_bidding_strategy_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_cpa_micros', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_roas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maximize_conv_target_cpa_micros', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maximize_conv_value_target_roas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('bidding_strategies_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bidding_strategies_pkey')),
    sa.UniqueConstraint('resource_name', name=op.f('bidding_strategies_resource_name_key'))
    )
    op.create_index(op.f('ix_bidding_strategies_id'), 'bidding_strategies', ['id'], unique=False)
    op.create_index(op.f('ix_bidding_strategies_google_bidding_strategy_id'), 'bidding_strategies', ['google_bidding_strategy_id'], unique=False)
    op.create_index(op.f('ix_bidding_strategies_client_id'), 'bidding_strategies', ['client_id'], unique=False)
    op.create_table('campaign_asset_performance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_asset_resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('field_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('conversions_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('view_through_conversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cost_micros', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('campaign_asset_performance_asset_id_fkey')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('campaign_asset_performance_campaign_id_fkey')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('campaign_asset_performance_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_asset_performance_pkey'))
    )
    op.create_index(op.f('ix_campaign_asset_performance_id'), 'campaign_asset_performance', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_asset_performance_client_id'), 'campaign_asset_performance', ['client_id'], unique=False)
    op.create_index(op.f('ix_campaign_asset_performance_campaign_id'), 'campaign_asset_performance', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_asset_performance_asset_id'), 'campaign_asset_performance', ['asset_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('google_asset_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('image_file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('youtube_video_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('youtube_video_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('call_to_action', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('assets_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_pkey')),
    sa.UniqueConstraint('resource_name', name=op.f('assets_resource_name_key'))
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_google_asset_id'), 'assets', ['google_asset_id'], unique=False)
    op.create_index(op.f('ix_assets_client_id'), 'assets', ['client_id'], unique=False)
    op.create_table('conversion_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('google_conversion_action_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('include_in_conversions_metric', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('primary_for_goal', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('default_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('always_use_default_value', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('conversion_actions_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversion_actions_pkey')),
    sa.UniqueConstraint('resource_name', name=op.f('conversion_actions_resource_name_key'))
    )
    op.create_index(op.f('ix_conversion_actions_id'), 'conversion_actions', ['id'], unique=False)
    op.create_index(op.f('ix_conversion_actions_google_conversion_action_id'), 'conversion_actions', ['google_conversion_action_id'], unique=False)
    op.create_index(op.f('ix_conversion_actions_client_id'), 'conversion_actions', ['client_id'], unique=False)
    op.create_table('asset_set_assets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_set_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('asset_set_assets_asset_id_fkey')),
    sa.ForeignKeyConstraint(['asset_set_id'], ['asset_sets.id'], name=op.f('asset_set_assets_asset_set_id_fkey')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('asset_set_assets_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_set_assets_pkey'))
    )
    op.create_index(op.f('ix_asset_set_assets_id'), 'asset_set_assets', ['id'], unique=False)
    op.create_index(op.f('ix_asset_set_assets_client_id'), 'asset_set_assets', ['client_id'], unique=False)
    op.create_index(op.f('ix_asset_set_assets_asset_set_id'), 'asset_set_assets', ['asset_set_id'], unique=False)
    op.create_index(op.f('ix_asset_set_assets_asset_id'), 'asset_set_assets', ['asset_id'], unique=False)
    op.drop_index(op.f('ix_run_new_checks_project_id'), table_name='run_new_checks')
    op.drop_index(op.f('ix_run_new_checks_id'), table_name='run_new_checks')
    op.drop_table('run_new_checks')
    # ### end Alembic commands ###
