import {
  BarChart3,
  Building2,
  ClipboardCheck,
  Gauge,
  Globe2,
  LayoutDashboard,
  Lightbulb,
  LineChart,
  Megaphone,
  MonitorSmartphone,
  NotebookPen,
  Palette,
  Rocket,
  Search,
  ShieldCheck,
  Sparkles,
  Target,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type ModuleId = "g-ads" | "seo" | "website";

export type ModuleFeature = {
  id: string;
  label: string;
  description: string;
  icon: LucideIcon;
};

export type ModuleDefinition = {
  id: ModuleId;
  label: string;
  shortLabel: string;
  description: string;
  icon: LucideIcon;
  defaultView: string;
  features: ModuleFeature[];
};

export const MODULE_DEFINITIONS: Record<ModuleId, ModuleDefinition> = {
  "g-ads": {
    id: "g-ads",
    label: "Google Ads",
    shortLabel: "G-Ads",
    description: "Automations, insights, and reporting for your Google Ads practice.",
    icon: Megaphone,
    defaultView: "dashboard",
    features: [
      {
        id: "dashboard",
        label: "Dashboard",
        description: "Account health, pacing, and alerts summarized in one place.",
        icon: LayoutDashboard,
      },
      {
        id: "accounts",
        label: "Accounts",
        description: "Manage clients, budgets, and campaigns in your portfolio.",
        icon: Building2,
      },
      {
        id: "recommendations",
        label: "AI Recommendations",
        description: "Action bundles and optimizations generated by the AI Analyst.",
        icon: Lightbulb,
      },
      {
        id: "reports",
        label: "Client Reports",
        description: "Automated reporting and preview flows for stakeholders.",
        icon: BarChart3,
      },
      {
        id: "checklist",
        label: "Setup Checklist",
        description: "Onboarding, integrations, and data validation tasks.",
        icon: ClipboardCheck,
      },
    ],
  },
  seo: {
    id: "seo",
    label: "Search Engine Optimization",
    shortLabel: "SEO",
    description: "Visibility, authority, and content workflows for search performance.",
    icon: Search,
    defaultView: "seo-overview",
    features: [
      {
        id: "seo-overview",
        label: "Overview",
        description: "Snapshot of crawl health, visibility, and top opportunities.",
        icon: LineChart,
      },
      {
        id: "web-errors",
        label: "Web Errors",
        description: "Cluster ideas, intent mapping, and content gap discovery.",
        icon: Target,
      },
      {
        id: "technical-seo",
        label: "Technical SEO",
        description: "AI-assisted briefs with SERP analysis and outline suggestions.",
        icon: NotebookPen,
      },
      {
        id: "content-seo",
        label: "Content SEO",
        description: "Track positions, competitors, and volatility across keywords.",
        icon: ShieldCheck,
      },
      {
        id: "links-seo",
        label: "Links SEO",
        description: "Track positions, competitors, and volatility across keywords.",
        icon: ShieldCheck,
      },
      {
        id: "speed-test",
        label: "Speed Test",
        description: "Track positions, competitors, and volatility across keywords.",
        icon: ShieldCheck,
      },
      {
        id: "ai-insights",
        label: "AI Insights",
        description: "Track positions, competitors, and volatility across keywords.",
        icon: ShieldCheck,
      },
    ],
  },
  website: {
    id: "website",
    label: "Website Experience",
    shortLabel: "Website",
    description: "Conversion, performance, and experimentation for web experiences.",
    icon: Globe2,
    defaultView: "website-overview",
    features: [
      {
        id: "website-dashboard",
        label: "Dashboard",
        description: "Account health, pacing, and alerts summarized in one place.",
        icon: MonitorSmartphone,
      },
      {
        id: "projects",
        label: "Projects",
        description: "Latency, LCP, and stability checks with remediation tips.",
        icon: Gauge,
      },
      {
        id: "inputs",
        label: "Inputs",
        description: "Landing page tuning, forms, and micro-conversion tracking.",
        icon: Rocket,
      },
      {
        id: "reports",
        label: "Reports",
        description: "A/B ideas, rollout plans, and impact tracking.",
        icon: Sparkles,
      },
      // {
      //   id: "brand-consistency",
      //   label: "Brand Consistency",
      //   description: "Styling, accessibility, and UX guardrails for editors.",
      //   icon: Palette,
      // },
    ],
  },
};

export const MODULE_IDS: ModuleId[] = ["g-ads", "seo", "website"];

export const MODULE_VIEW_ROUTES: Record<ModuleId, Record<string, string>> = {
  "g-ads": {
    dashboard: "/dashboard",
    accounts: "/accounts",
    recommendations: "/recommendations",
    reports: "/reports",
    checklist: "/checklist",
  },
  seo: {
    "seo-overview": "/modules/seo/overview",
    "web-errors": "/modules/seo/web-errors",
    "technical-seo": "/modules/seo/technical-seo",
    "content-seo": "/modules/seo/content-seo",
    "links-seo": "/modules/seo/links-seo",
    "speed-test": "/modules/seo/speed-test",
    "ai-insights": "/modules/seo/ai-insights",
  },
  website: {
    "website-overview": "/modules/website/overview",
    "site-performance": "/modules/website/performance",
    "conversion-lab": "/modules/website/conversion-lab",
    experiments: "/modules/website/experiments",
    "brand-consistency": "/modules/website/brand-consistency",
  },
};

export const GLOBAL_VIEW_ROUTES: Record<string, string> = {
  settings: "/settings",
  users: "/users",
};

export function isModuleId(value: string): value is ModuleId {
  return MODULE_IDS.includes(value as ModuleId);
}

export function getModuleDefaultRoute(moduleId: ModuleId): string {
  const module = MODULE_DEFINITIONS[moduleId];
  const routes = MODULE_VIEW_ROUTES[moduleId];
  return routes[module.defaultView] ?? "/dashboard";
}
