import {
  AlertCircle,
  BarChart3,
  Building2,
  ClipboardCheck,
  FileText,
  Globe2,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Link2, Settings,
  Megaphone, ClipboardList,
  Search, LogIn,
  Settings2,
  Sparkles, FolderOpen,
  Zap
} from "lucide-react";


export type ModuleId = "g-ads" | "seo" | "website";

export type ModuleFeature = {
  id: string;
  label: string;
  description?: string;
  icon: LucideIcon;
};

export type ModuleDefinition = {
  id: ModuleId;
  label: string;
  shortLabel: string;
  description: string;
  icon: LucideIcon;
  defaultView: string;
  features: ModuleFeature[];
};

export const MODULE_DEFINITIONS: Record<ModuleId, ModuleDefinition> = {
  "g-ads": {
    id: "g-ads",
    label: "Google Ads",
    shortLabel: "G-Ads",
    description: "Automations, insights, and reporting for your Google Ads practice.",
    icon: Megaphone,
    defaultView: "dashboard",
    features: [
      {
        id: "dashboard",
        label: "Dashboard",
        description: "Account health, pacing, and alerts summarized in one place.",
        icon: LayoutDashboard,
      },
      {
        id: "accounts",
        label: "Accounts",
        description: "Manage clients, budgets, and campaigns in your portfolio.",
        icon: Building2,
      },
      {
        id: "recommendations",
        label: "AI Recommendations",
        description: "Action bundles and optimizations generated by the AI Analyst.",
        icon: Lightbulb,
      },
      {
        id: "reports",
        label: "Client Reports",
        description: "Automated reporting and preview flows for stakeholders.",
        icon: BarChart3,
      },
      {
        id: "checklist",
        label: "Setup Checklist",
        description: "Onboarding, integrations, and data validation tasks.",
        icon: ClipboardCheck,
      },
    ],
  },
  seo: {
    id: "seo",
    label: "SEO",
    shortLabel: "SEO",
    description: "Visibility, authority, and content workflows for search performance.",
    icon: Search,
    defaultView: "seo-overview",
    features: [
      { id: "seo-overview", label: "Overview", icon: LayoutGrid },
      { id: "web-errors", label: "Web Errors", icon: AlertCircle },
      { id: "technical-seo", label: "Technical SEO", icon: Settings2 },
      { id: "content-seo", label: "Content SEO", icon: FileText },
      { id: "links-seo", label: "Links SEO", icon: Link2 },
      { id: "speed-test", label: "Speed Test", icon: Zap },
      { id: "ai-insights", label: "AI Insights", icon: Sparkles },
    ],
  },
  website: {
    id: "website",
    label: "Website",
    shortLabel: "Website",
    description: "Conversion, performance, and experimentation for web experiences.",
    icon: Globe2,
    defaultView: "website-dashboard",
    features: [
      {
        id: "website-dashboard",
        label: "Dashboard",
        icon: LayoutGrid,
      },
      {
        id: "inputs",
        label: "Inputs",
        icon: LogIn,
      },
      {
        id: "projects",
        label: "Projects",
        icon: FolderOpen,
      },
      {
        id: "reports",
        label: "Reports",
        icon: ClipboardList,
      },
      {
        id: "website-settings",
        label: "Project Settings",
        icon: Settings,
      },
      // {
      //   id: "brand-consistency",
      //   label: "Brand Consistency",
      //   description: "Styling, accessibility, and UX guardrails for editors.",
      //   icon: Palette,
      // },
    ],
  },
};

export const MODULE_IDS: ModuleId[] = ["g-ads", "seo", "website"];

export const MODULE_VIEW_ROUTES: Record<ModuleId, Record<string, string>> = {
  "g-ads": {
    dashboard: "/dashboard",
    accounts: "/accounts",
    recommendations: "/recommendations",
    reports: "/reports",
    checklist: "/checklist",
  },
  seo: {
    "seo-overview": "/modules/seo/overview",
    "web-errors": "/modules/seo/web-errors",
    "technical-seo": "/modules/seo/technical-seo",
    "content-seo": "/modules/seo/content-seo",
    "links-seo": "/modules/seo/links-seo",
    "speed-test": "/modules/seo/speed-test",
    "ai-insights": "/modules/seo/ai-insights",
  },
  website: {
    "website-dashboard": "/modules/website/dashboard",
    "projects": "/modules/website/projects",
    "inputs": "/modules/website/inputs",
    "reports": "/modules/website/reports",
    "website-settings": "/modules/website/settings",
  },
};

export const GLOBAL_VIEW_ROUTES: Record<string, string> = {
  settings: "/settings",
  users: "/users",
};

export function isModuleId(value: string): value is ModuleId {
  return MODULE_IDS.includes(value as ModuleId);
}

export function getModuleDefaultRoute(moduleId: ModuleId): string {
  const module = MODULE_DEFINITIONS[moduleId];
  const routes = MODULE_VIEW_ROUTES[moduleId];
  return routes[module.defaultView] ?? "/dashboard";
}
